### PR TITLE
Address issue 227 by adopting XDG config convention

### PR DESCRIPTION
**Pull request by seancorfield**
This addresses #227 by:

* Changing the default `config.edn` location to the XDG location (default `~/.config/polylith/config.edn` but overridable via the `XDG_CONFIG_HOME` environment variable).
* Adding a migration of `~/.polylith/config.edn` to the new location, adding a comment in the old file so any projects still using older `poly` versions can still read it.

> Note: I'm not sure how Circle CI will handle environment variable syntax in `config.yml` but I've tried to make it work regardless of `XDG_CONFIG_HOME` being set; If that breaks it, just changing to `~/.config/polylith` in those four lines should solve it.

### CODE REVIEW

**Comment by seancorfield** [comment]
Apparently, the Circle CI updates were acceptable. ~The conflicts are cosmetic and seem to reflect a difference due to the pluggable test runner change (which I thought was on master and I _thought_ I was all merged up to date but apparently not -- LMK if you want me to fix the PR).~ PR updated after full rebasing.

**Review by tengstrand — CHANGES_REQUESTED** [review]
Hi Sean!
This looks great to me. I have just tested it on my machine, which is not an XGD system, and it seems to work as before. I will approve this if you update polylith.clj.core.version.interface with the correct issue and date, e.g.:

(def revision "alpha-issue227-01")
(def date "2022-05-29")

I need to update the gitbook documentation also, branch "Release 0.2.15" (that's the downside of letting the documentation live in a separate repo).

**Comment by seancorfield** [comment]
Updates made.

**Review by tengstrand — APPROVED** [review]
Thanks!

**Pull request merged**
